# Generated by Django 2.1.2 on 2019-09-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='dateStarted',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
