# Generated by Django 2.2.5 on 2019-09-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20190908_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='expectedMonthlyIncome',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='totalMonthlyExpenses',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='categorylimitandspent',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='categorylimitandspent',
            name='spent',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='monthlyPayment',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
