# Generated by Django 2.2.5 on 2019-09-30 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20190925_1647'),
        ('budget', '0003_auto_20190920_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goalAmount',
        ),
        migrations.AddField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account'),
        ),
    ]
