# Generated by Django 2.2.5 on 2019-09-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20190930_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goalAmount',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=15),
            preserve_default=False,
        ),
    ]
