# Generated by Django 2.2.5 on 2019-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_remove_goal_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='savingOrPayingoff',
            field=models.CharField(default=7, max_length=10),
            preserve_default=False,
        ),
    ]
