# Generated by Django 2.2.5 on 2019-10-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20191001_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='interest',
        ),
    ]
