# Generated by Django 2.2.5 on 2019-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_remove_goal_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='savingOrPayingoff',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
    ]
