# Generated by Django 2.1.5 on 2019-03-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=40)),
                ('accountType', models.CharField(blank=True, choices=[('c', 'Checking'), ('s', 'Savings'), ('l', 'Loan'), ('i', 'Investment')], help_text='type of account', max_length=1)),
                ('accountNumber', models.CharField(max_length=40)),
                ('balance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('vendor', models.TextField()),
                ('datePosted', models.CharField(max_length=100)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('profilePicture', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='accountUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserProfile'),
        ),
    ]
