# Generated by Django 2.1.5 on 2019-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190410_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accountNumber',
        ),
        migrations.RemoveField(
            model_name='account',
            name='accountUser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.AddField(
            model_name='account',
            name='currenctCode',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='mask',
            field=models.CharField(default=-1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=-1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='officialName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balanceAvailable',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
