# Generated by Django 2.1.5 on 2019-04-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190417_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balanceCurrent',
            field=models.IntegerField(null=True),
        ),
    ]
