# Generated by Django 2.1.5 on 2019-04-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190417_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currenctCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
