# Generated by Django 2.1.5 on 2019-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190417_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='officialName',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
