# Generated by Django 2.1.5 on 2019-04-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190417_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendor',
        ),
    ]
