# Generated by Django 2.1.5 on 2019-04-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190422_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Account',
        ),
    ]
