# Generated by Django 2.1.5 on 2019-05-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categoryBottom',
            field=models.CharField(default='iuhij', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='categoryMiddle',
            field=models.CharField(default='fghjk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='categoryTop',
            field=models.CharField(default='jhgf', max_length=100),
            preserve_default=False,
        ),
    ]
