# Generated by Django 2.1.5 on 2019-05-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190521_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='categoryBottom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='categoryMiddle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='categoryTop',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
