# Generated by Django 2.1.5 on 2019-05-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190521_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accountID',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Account'),
        ),
    ]
