# Generated by Django 2.1.5 on 2019-05-24 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190524_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountID',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
