# Generated by Django 2.1.2 on 2019-08-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_account_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accessToken',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
