# Generated by Django 2.1.2 on 2019-08-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_account_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='itemID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
