# Generated by Django 2.1.2 on 2019-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_assetliabilityobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetliabilityobject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
