# Generated by Django 2.2.5 on 2019-09-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_assetliabilityobject_owed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetliabilityobject',
            name='owed',
            field=models.IntegerField(null=True),
        ),
    ]
