# Generated by Django 2.2.5 on 2019-09-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20190920_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetwithaccountobject',
            old_name='account',
            new_name='owed',
        ),
    ]
