# Generated by Django 2.2.5 on 2019-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20190920_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetliabilityobject',
            name='equity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetwithaccountobject',
            name='equity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
