# Generated by Django 2.2.5 on 2019-09-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20190920_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='User',
            new_name='user',
        ),
    ]
